### ISSUE TITLE
docker run ... and docker exec ... can not work when they are putted together in a shell script.

### ISSUE THREAD

**Issue by ybdong919** [The-Sequence-Ontology/GAL#6]
Hi,
I try to use docker run and docker exec for GAL. 
The two commands are :
1. docker run -dit --name 174 -v /local/directory/:/usr/GAL_data
2. docker exec 174 python3 /usr/GAL/gal_manage.py --orconfig=/usr/GAL_data/111.ini

In a terminal, when I separately run the two commands one by one, they both work. 

However, when I write them in a shell script and run the shell script, the command "docker exec..." always does not work. The errors shown out is: 

4a603795c15dfd53a37ea9dee142816c584237f2e277136284fb1cdce1f83236
GAL Upload started 

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 920, in connect
    **kwargs)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/GAL/gal_manage.py", line 24, in <module>
    main.process_schema_common_data(db_config, arg, CurrDir)
  File "/usr/GAL/main.py", line 85, in process_schema_common_data
    db_function.check_db_connection(db_config.host, db_config.db_username, db_config.db_password)
  File "/usr/GAL/galpy/db_function.py", line 100, in check_db_connection
    db = pymysql.connect(host, db_username, db_password)
  File "/usr/lib/python3/dist-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 967, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 99] Cannot assign requested address)")

**Comment by srynobio** [comment]
It appears the above errors are Python related (more specifically python-mysql), GAL is a toolset written in Perl and so are not related to the errors you are seeing.

Additionally at this time GAL is not under active development.

**Comment by ybdong919** [comment]
The weird thing is when the two command run separately one by one in a
terminal, they both work. No any error show out.
However, we put them in a shell  script ,  the second command will not
work.
Do you know why?
